version: "3.9"

services:
  postgresql:
    image: postgres:14
    container_name: test-jsblog-postgredb
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./postgres-backup.sql:/docker-entrypoint-initdb.d/postgres-backup.sql
  redis:
    image: redis:latest
    container_name: test-jsblog-redis
    ports:
      - 6379:6379
