version: "3.9"

services:
  postgresql:
    image: postgres:14
    container_name: jsblog-app-postgredb
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./postgres-backup.sql:/docker-entrypoint-initdb.d/postgres-backup.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    container_name: jsblog-app-redis
    ports:
      - 6379:6379
  jsblog-server:
    container_name: jsblog-app-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      postgresql:
        condition: service_healthy
